global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'pyroscope'
    static_configs:
      - targets: ['pyroscope:4040']
  - job_name: 'collector'
    static_configs:
      - targets: ['collector:8080']