global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pyroscope'
    static_configs:
      - targets: ['pyroscope:4040']

  - job_name: 'collector-metrics'
    static_configs:
      - targets: ['collector-metrics:9100']

  - job_name: 'processor-metrics'
    static_configs:
      - targets: ['processor-metrics:9100']

  - job_name: 'trader-metrics'
    static_configs:
      - targets: ['trader-metrics:9100']